### ISSUE TITLE
Redis errors when running import script

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_forum#45]
This type of errors arrive ramdomly when running import script.
Here, the real import do not have started yet, it appends during the settings change for the import.
I relaunch the script and all works perfectly.

```
$ ./import_run.sh 
You are running an old version of bundler, please upgrade bundler ASAP, if you are using Discourse docker, rebuild your container.
You are running an old version of bundler, please upgrade bundler ASAP, if you are using Discourse docker, rebuild your container.
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (2.7ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "users" LIMIT 20) subquery_for_count 
URGENT: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error. Failed to initialize site default
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0   User Load (2.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = -1 LIMIT 1  [["id", -1]] 
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (2.1ms)  SELECT "translation_overrides"."translation_key", "translation_overrides"."value" FROM "translation_overrides" WHERE "translation_overrides"."locale" = 'en'  [["locale", :en]] 
loading existing groups...
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (0.8ms)  SELECT "group_custom_fields"."group_id", "group_custom_fields"."value" FROM "group_custom_fields" WHERE "group_custom_fields"."name" = 'import_id'  [["name", "import_id"]] 
loading existing users...
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (1.5ms)  SELECT "user_custom_fields"."user_id", "user_custom_fields"."value" FROM "user_custom_fields" WHERE "user_custom_fields"."name" = 'import_id'  [["name", "import_id"]] 
loading existing categories...
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (1.0ms)  SELECT "category_custom_fields"."category_id", "category_custom_fields"."value" FROM "category_custom_fields" WHERE "category_custom_fields"."name" = 'import_id'  [["name", "import_id"]] 
loading existing posts...
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (0.9ms)  SELECT "post_custom_fields"."post_id", "post_custom_fields"."value" FROM "post_custom_fields" WHERE "post_custom_fields"."name" = 'import_id'  [["name", "import_id"]] 
loading existing posts2...
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (2.1ms)  SELECT "posts"."id", "posts"."user_id", "posts"."topic_id", "posts"."post_number" FROM "posts" WHERE ("posts"."deleted_at" IS NULL) 
loading existing topics...
Failed to report error: EXECABORT Transaction discarded because of previous errors. 0    (4.1ms)  SELECT posts.id, posts.topic_id, posts.post_number, topics.slug FROM "posts" INNER JOIN "topics" ON "topics"."id" = "posts"."topic_id" AND ("topics"."deleted_at" IS NULL) WHERE ("posts"."deleted_at" IS NULL) 
/home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis/pipeline.rb:79:in `finish': EXECABORT Transaction discarded because of previous errors. (Redis::CommandError)
    from /home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:150:in `block in call_pipeline'
    from /home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
    from /home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:148:in `call_pipeline'
    from /home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:2245:in `block in multi'
    from /home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
    from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    from /home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
    from /home/amorvan/gempath/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:2237:in `multi'
    from /home/amorvan/gempath/ruby/2.1.0/gems/message_bus-2.0.0.beta.2/lib/message_bus/redis/reliable_pub_sub.rb:92:in `publish'
    from /home/amorvan/gempath/ruby/2.1.0/gems/message_bus-2.0.0.beta.2/lib/message_bus.rb:218:in `publish'
    from /home/amorvan/c2corgv6/discourse/lib/site_setting_extension.rb:322:in `notify_changed!'
    from /home/amorvan/c2corgv6/discourse/lib/site_settings/db_provider.rb:7:in `block in initialize'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `instance_exec'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `block in make_lambda'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:263:in `call'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:263:in `block in simple'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `block in call'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `each'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_commit_callbacks'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:314:in `committed!'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:89:in `commit_records'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `commit'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `commit_transaction'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `within_new_transaction'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    from /home/amorvan/gempath/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:291:in `save!'
    from /home/amorvan/c2corgv6/discourse/lib/site_settings/db_provider.rb:40:in `save'
    from /home/amorvan/c2corgv6/discourse/lib/site_setting_extension.rb:315:in `add_override!'
    from /home/amorvan/c2corgv6/discourse/lib/site_setting_extension.rb:466:in `block in setup_methods'
    from /home/amorvan/c2corgv6/discourse/lib/site_setting_extension.rb:364:in `set'
    from /home/amorvan/c2corgv6/discourse/script/import_scripts/base.rb:92:in `block in reset_site_settings'
    from /home/amorvan/c2corgv6/discourse/script/import_scripts/base.rb:90:in `each'
    from /home/amorvan/c2corgv6/discourse/script/import_scripts/base.rb:90:in `reset_site_settings'
    from /home/amorvan/c2corgv6/discourse/script/import_scripts/base.rb:61:in `ensure in perform'
    from /home/amorvan/c2corgv6/discourse/script/import_scripts/base.rb:61:in `perform'
    from script/import_scripts/punbb.rb:499:in `<main>'
```

**Comment by arnaud-morvan** [comment]
To disable query cache globally : http://stackoverflow.com/questions/20366262/disabling-rails-sql-query-caching-globally
I will try it soon

**Comment by stef74** [comment]
@arnaud-morvan issue allready exist ?

**Comment by arnaud-morvan** [comment]
Seems related to available disk space. This do not append anymore on any server. Closing.
